# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: in_sdk_body_appmodule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='in_sdk_body_appmodule.proto',
  package='insider.sdk',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bin_sdk_body_appmodule.proto\x12\x0binsider.sdk\"\x96\x01\n\x11\x41ppModuleBaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x12*\n\x05state\x18\x03 \x01(\x0e\x32\x1b.insider.sdk.AppModuleState\x12\x37\n\npermission\x18\x04 \x01(\x0e\x32#.insider.sdk.AppModuleCfgPermission\"\x85\x01\n\x11\x41ppModuleCoutInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x31\n\trun_state\x18\x02 \x01(\x0e\x32\x1e.insider.sdk.AppModuleRunState\x12\x31\n\tbase_info\x18\x03 \x01(\x0b\x32\x1e.insider.sdk.AppModuleBaseInfo\"L\n\x15\x41ppModuleCoutInfoList\x12\x33\n\x0b\x61pp_modules\x18\x01 \x03(\x0b\x32\x1e.insider.sdk.AppModuleCoutInfo*p\n\x0e\x41ppModuleState\x12\x15\n\x11\x45_APP_MODULE_IDLE\x10\x00\x12\x15\n\x11\x45_APP_MODULE_INIT\x10\x01\x12\x1a\n\x16\x45_APP_MODULE_INSTALLED\x10\x02\x12\x14\n\x10\x45_APP_MODULE_BAD\x10\x03*m\n\x11\x41ppModuleRunState\x12\x1a\n\x16\x45_APP_MODULE_RUN_ST_OK\x10\x00\x12\x1b\n\x17\x45_APP_MODULE_RUN_ST_ERR\x10\x01\x12\x1f\n\x1b\x45_APP_MODULE_RUN_ST_UNKNOWN\x10\x02*k\n\x16\x41ppModuleCfgPermission\x12&\n\"E_APP_MODULE_CFG_PERMISSION_ENABLE\x10\x00\x12)\n%E_APP_MODULE_CFG_PERMISSION_DISENABLE\x10\x01\x62\x06proto3')
)

_APPMODULESTATE = _descriptor.EnumDescriptor(
  name='AppModuleState',
  full_name='insider.sdk.AppModuleState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_INIT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_INSTALLED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_BAD', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=411,
  serialized_end=523,
)
_sym_db.RegisterEnumDescriptor(_APPMODULESTATE)

AppModuleState = enum_type_wrapper.EnumTypeWrapper(_APPMODULESTATE)
_APPMODULERUNSTATE = _descriptor.EnumDescriptor(
  name='AppModuleRunState',
  full_name='insider.sdk.AppModuleRunState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_RUN_ST_OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_RUN_ST_ERR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_RUN_ST_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=525,
  serialized_end=634,
)
_sym_db.RegisterEnumDescriptor(_APPMODULERUNSTATE)

AppModuleRunState = enum_type_wrapper.EnumTypeWrapper(_APPMODULERUNSTATE)
_APPMODULECFGPERMISSION = _descriptor.EnumDescriptor(
  name='AppModuleCfgPermission',
  full_name='insider.sdk.AppModuleCfgPermission',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_CFG_PERMISSION_ENABLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E_APP_MODULE_CFG_PERMISSION_DISENABLE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=636,
  serialized_end=743,
)
_sym_db.RegisterEnumDescriptor(_APPMODULECFGPERMISSION)

AppModuleCfgPermission = enum_type_wrapper.EnumTypeWrapper(_APPMODULECFGPERMISSION)
E_APP_MODULE_IDLE = 0
E_APP_MODULE_INIT = 1
E_APP_MODULE_INSTALLED = 2
E_APP_MODULE_BAD = 3
E_APP_MODULE_RUN_ST_OK = 0
E_APP_MODULE_RUN_ST_ERR = 1
E_APP_MODULE_RUN_ST_UNKNOWN = 2
E_APP_MODULE_CFG_PERMISSION_ENABLE = 0
E_APP_MODULE_CFG_PERMISSION_DISENABLE = 1



_APPMODULEBASEINFO = _descriptor.Descriptor(
  name='AppModuleBaseInfo',
  full_name='insider.sdk.AppModuleBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='insider.sdk.AppModuleBaseInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable', full_name='insider.sdk.AppModuleBaseInfo.enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='insider.sdk.AppModuleBaseInfo.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='permission', full_name='insider.sdk.AppModuleBaseInfo.permission', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=195,
)


_APPMODULECOUTINFO = _descriptor.Descriptor(
  name='AppModuleCoutInfo',
  full_name='insider.sdk.AppModuleCoutInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='insider.sdk.AppModuleCoutInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_state', full_name='insider.sdk.AppModuleCoutInfo.run_state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base_info', full_name='insider.sdk.AppModuleCoutInfo.base_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=331,
)


_APPMODULECOUTINFOLIST = _descriptor.Descriptor(
  name='AppModuleCoutInfoList',
  full_name='insider.sdk.AppModuleCoutInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_modules', full_name='insider.sdk.AppModuleCoutInfoList.app_modules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=409,
)

_APPMODULEBASEINFO.fields_by_name['state'].enum_type = _APPMODULESTATE
_APPMODULEBASEINFO.fields_by_name['permission'].enum_type = _APPMODULECFGPERMISSION
_APPMODULECOUTINFO.fields_by_name['run_state'].enum_type = _APPMODULERUNSTATE
_APPMODULECOUTINFO.fields_by_name['base_info'].message_type = _APPMODULEBASEINFO
_APPMODULECOUTINFOLIST.fields_by_name['app_modules'].message_type = _APPMODULECOUTINFO
DESCRIPTOR.message_types_by_name['AppModuleBaseInfo'] = _APPMODULEBASEINFO
DESCRIPTOR.message_types_by_name['AppModuleCoutInfo'] = _APPMODULECOUTINFO
DESCRIPTOR.message_types_by_name['AppModuleCoutInfoList'] = _APPMODULECOUTINFOLIST
DESCRIPTOR.enum_types_by_name['AppModuleState'] = _APPMODULESTATE
DESCRIPTOR.enum_types_by_name['AppModuleRunState'] = _APPMODULERUNSTATE
DESCRIPTOR.enum_types_by_name['AppModuleCfgPermission'] = _APPMODULECFGPERMISSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppModuleBaseInfo = _reflection.GeneratedProtocolMessageType('AppModuleBaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _APPMODULEBASEINFO,
  '__module__' : 'in_sdk_body_appmodule_pb2'
  # @@protoc_insertion_point(class_scope:insider.sdk.AppModuleBaseInfo)
  })
_sym_db.RegisterMessage(AppModuleBaseInfo)

AppModuleCoutInfo = _reflection.GeneratedProtocolMessageType('AppModuleCoutInfo', (_message.Message,), {
  'DESCRIPTOR' : _APPMODULECOUTINFO,
  '__module__' : 'in_sdk_body_appmodule_pb2'
  # @@protoc_insertion_point(class_scope:insider.sdk.AppModuleCoutInfo)
  })
_sym_db.RegisterMessage(AppModuleCoutInfo)

AppModuleCoutInfoList = _reflection.GeneratedProtocolMessageType('AppModuleCoutInfoList', (_message.Message,), {
  'DESCRIPTOR' : _APPMODULECOUTINFOLIST,
  '__module__' : 'in_sdk_body_appmodule_pb2'
  # @@protoc_insertion_point(class_scope:insider.sdk.AppModuleCoutInfoList)
  })
_sym_db.RegisterMessage(AppModuleCoutInfoList)


# @@protoc_insertion_point(module_scope)
